{
 "title": "stream-loaders",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_consumer_fetch_manager_metrics_bytes_consumed_total_by_topic,topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Watermark delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "min(stream_loader_source_watermark_delay_ms < 6.048e+8) by (topic, partition)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offset lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_metrics_records_lag_by_partition_topic) by (topic, partition)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records Batched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(stream_loader_batch_records_batched_total{topic=~\"[[topic:regex]]\"}[1m])) by (topic,partition)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records Written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(stream_loader_batch_records_written_total{topic=~\"[[topic:regex]]\"}[1m])) by (topic,partition)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Written minus Batched - pass-though",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(stream_loader_batch_records_batched_total{topic=~\"[[topic:regex]]\"}[1m])) by (topic,partition) - sum(rate(stream_loader_batch_records_written_total{topic=~\"[[topic:regex]]\"}[1m])) by (topic,partition)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duplicates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(sink_duplicates_total[1m])) by (partition)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File hourly rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(3600*rate(stream_loader_batch_commit_duration_seconds_count{}[30m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File commit duration 99.9 Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.999, rate(stream_loader_batch_commit_duration_seconds_bucket{}[20s]))) by (loaded_thread, partition_group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(stream_loader_batch_commit_queue_size) by (job)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}